cmake_minimum_required(VERSION 3.28)
if(NOT DEFINED ROOT)
 get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
function(check_decorations file approved)
 if(NOT EXISTS "${file}")
  message(FATAL_ERROR "Missing decorations: ${file}")
 endif()
 get_filename_component(base "${file}" DIRECTORY)
 file(READ "${file}" data)
 string(JSON count LENGTH "${data}" items)
 if(count EQUAL 0)
  return()
 endif()
 math(EXPR last "${count}-1")
 foreach(i RANGE 0 ${last})
  string(JSON image GET "${data}" items ${i} image)
  if(IS_ABSOLUTE "${image}")
   message(FATAL_ERROR "Relative decoration image required")
  endif()
  file(REAL_PATH "${base}/${image}" path)
  file(RELATIVE_PATH relative "${ROOT}" "${path}")
  string(TOLOWER "${relative}" relative)
  if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}" OR relative MATCHES "^[.][.](/|$)" OR relative MATCHES "^build/")
   message(FATAL_ERROR "Invalid decoration image path: ${path}")
  endif()
  if(approved AND (NOT relative MATCHES "^assets/decorations/.+/runtime/[^/]+[.]png$" OR relative MATCHES "/runtime/trials/"))
   message(FATAL_ERROR "Approved decoration must use runtime outside trials: ${path}")
  endif()
  if(approved OR relative MATCHES "/runtime/trials/")
   string(REGEX REPLACE "[.]png$" ".provenance.json" provenance "${path}")
   file(READ "${provenance}" record)
   string(JSON status GET "${record}" status)
   string(JSON expected GET "${record}" sha256)
   file(SHA256 "${path}" actual)
   if(NOT expected STREQUAL actual)
    message(FATAL_ERROR "Decoration hash mismatch: ${path}")
   endif()
   if(approved)
    get_filename_component(name "${path}" NAME)
    string(JSON runtime GET "${record}" runtime_file)
    if(NOT status STREQUAL "approved" OR NOT runtime STREQUAL name)
     message(FATAL_ERROR "Invalid approved decoration provenance")
    endif()
   elseif(NOT status STREQUAL "trial")
    message(FATAL_ERROR "Invalid trial decoration provenance")
   endif()
  endif()
 endforeach()
endfunction()
if(DEFINED CHECK_FILE)
 check_decorations("${CHECK_FILE}" "${APPROVED}")
 return()
endif()
file(GLOB regions "${ROOT}/assets/regions/*.json")
foreach(region IN LISTS regions)
 file(READ "${region}" data)
 string(JSON name ERROR_VARIABLE absent GET "${data}" decorations)
 if(absent)
  continue()
 endif()
 if(NOT name MATCHES "^[a-z0-9_]+$" OR name MATCHES "trial")
  message(FATAL_ERROR "Invalid default decoration name: ${name}")
 endif()
 check_decorations("${ROOT}/assets/decorations/${name}.json" TRUE)
endforeach()
file(GLOB trials "${ROOT}/assets/decorations/*_trial.json")
foreach(file IN LISTS trials)
 check_decorations("${file}" FALSE)
endforeach()
# Positive and negative fixtures exercise the exact checker, without repository assets.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef id)
set(fixture "${ROOT}/build/approved_decoration_checks/${id}")
set(base "${fixture}/assets/decorations/test/runtime")
file(MAKE_DIRECTORY "${base}/trials")
file(WRITE "${base}/test.png" "fixture")
file(SHA256 "${base}/test.png" hash)
file(WRITE "${base}/test.provenance.json" "{\"status\":\"approved\",\"runtime_file\":\"test.png\",\"sha256\":\"${hash}\"}")
set(config "${fixture}/assets/decorations/default.json")
file(WRITE "${config}" "{\"items\":[{\"image\":\"test/runtime/test.png\"}]}")
execute_process(COMMAND "${CMAKE_COMMAND}" -DROOT=${fixture} -DCHECK_FILE=${config} -DAPPROVED=ON -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
 message(FATAL_ERROR "Valid decoration fixture rejected")
endif()
foreach(case IN ITEMS trials hash)
 if(case STREQUAL "trials")
  file(WRITE "${base}/trials/test.png" "fixture")
  file(WRITE "${config}" "{\"items\":[{\"image\":\"test/runtime/trials/test.png\"}]}")
  set(expected "outside trials")
 else()
  file(WRITE "${config}" "{\"items\":[{\"image\":\"test/runtime/test.png\"}]}")
  file(WRITE "${base}/test.png" "changed")
  set(expected "hash mismatch")
 endif()
 execute_process(COMMAND "${CMAKE_COMMAND}" -DROOT=${fixture} -DCHECK_FILE=${config} -DAPPROVED=ON -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE code ERROR_VARIABLE error)
 if(code EQUAL 0 OR NOT error MATCHES "${expected}")
  message(FATAL_ERROR "Decoration counterexample not detected: ${case}: ${error}")
 endif()
endforeach()
message(STATUS "APPROVED DECORATION CHECKS PASS")
