cmake_minimum_required(VERSION 3.28)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(GLOB regions "${root}/assets/regions/*.json")
file(GLOB_RECURSE manifests "${root}/assets/tiles/*.manifest.json")
include("${CMAKE_CURRENT_LIST_DIR}/TilesetImageChecks.cmake")
# Counterexamples: an ancestor named build is valid; repository build and escape are not.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run)
set(fixture "${root}/build/path_checks/${run}/build/repository")
file(MAKE_DIRECTORY "${fixture}/assets" "${fixture}/build")
file(WRITE "${fixture}/assets/image.png" "fixture")
file(WRITE "${fixture}/build/image.png" "fixture")
file(WRITE "${fixture}/../outside.png" "fixture")
image_allowed("${fixture}" "${fixture}/assets/image.png" valid)
image_allowed("${fixture}" "${fixture}/build/image.png" generated)
image_allowed("${fixture}" "${fixture}/../outside.png" escaped)
if(NOT valid OR generated OR escaped)
  message(FATAL_ERROR "Repository-relative image path counterexamples failed")
endif()
set(checked 0)
foreach(region IN LISTS regions)
  file(READ "${region}" data)
  string(JSON name ERROR_VARIABLE absent GET "${data}" tileset)
  if(absent)
    continue()
  endif()
  set(file "${root}/assets/tilesets/${name}.json")
  get_filename_component(base "${file}" DIRECTORY)
  file(READ "${file}" tileset)
  string(JSON image GET "${tileset}" image)
  check_image("${base}/${image}")
  string(JSON count ERROR_VARIABLE absent LENGTH "${tileset}" sampling)
  if(NOT absent AND count GREATER 0)
    math(EXPR last "${count}-1")
    foreach(i RANGE 0 ${last})
      string(JSON role MEMBER "${tileset}" sampling ${i})
      string(JSON image GET "${tileset}" sampling "${role}" image)
      check_image("${base}/${image}")
      if(NOT role STREQUAL "inner")
        continue()
      endif()
      file(REAL_PATH "${base}/${image}" inner)
      set(found FALSE)
      foreach(manifest IN LISTS manifests)
        file(READ "${manifest}" pipeline)
        get_filename_component(pipeline_base "${manifest}" DIRECTORY)
        string(JSON candidates LENGTH "${pipeline}" candidates)
        math(EXPR final "${candidates}-1")
        foreach(c RANGE 0 ${final})
          string(JSON approved ERROR_VARIABLE absent GET "${pipeline}" candidates ${c} approved_runtime_candidate)
          if(absent OR NOT approved)
            continue()
          endif()
          string(JSON approval_type TYPE "${pipeline}" candidates ${c} approved_runtime_candidate)
          if(NOT approval_type STREQUAL "BOOLEAN")
            message(FATAL_ERROR "Approval must be a boolean: ${manifest}")
          endif()
          string(JSON runtime GET "${pipeline}" candidates ${c} runtime_file)
          file(REAL_PATH "${pipeline_base}/${runtime}" candidate_image)
          if(NOT candidate_image STREQUAL inner)
            continue()
          endif()
          string(REGEX REPLACE "[.]png$" ".provenance.json" record_file "${inner}")
          file(READ "${record_file}" record)
          string(JSON id GET "${pipeline}" candidates ${c} id)
          string(JSON recorded_id GET "${record}" candidate)
          string(JSON recorded_runtime GET "${record}" runtime_file)
          string(JSON expected_hash GET "${record}" runtime_sha256)
          file(SHA256 "${inner}" actual_hash)
          if(NOT id STREQUAL recorded_id OR NOT runtime STREQUAL recorded_runtime OR NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Approved runtime provenance mismatch: ${inner}")
          endif()
          set(found TRUE)
        endforeach()
      endforeach()
      if(NOT found)
        message(FATAL_ERROR "Default inner image has no manifest approval: ${inner}")
      endif()
    endforeach()
  endif()
  math(EXPR checked "${checked}+1")
  message(STATUS "Approved default checked: ${region} -> ${name}")
endforeach()
message(STATUS "DEFAULT TILESET CHECKS PASS: ${checked} tilesets across all region files")
