cmake_minimum_required(VERSION 3.28)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(GLOB regions "${root}/assets/regions/*.json")
file(GLOB_RECURSE manifests "${root}/assets/tiles/*.manifest.json")
include("${CMAKE_CURRENT_LIST_DIR}/TilesetImageChecks.cmake")
# Counterexamples: an ancestor named build is valid; repository build and escape are not.
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run)
set(fixture "${root}/build/path_checks/${run}/build/repository")
file(MAKE_DIRECTORY "${fixture}/assets" "${fixture}/build")
file(WRITE "${fixture}/assets/image.png" "fixture")
file(WRITE "${fixture}/build/image.png" "fixture")
file(WRITE "${fixture}/../outside.png" "fixture")
image_allowed("${fixture}" "${fixture}/assets/image.png" valid)
image_allowed("${fixture}" "${fixture}/build/image.png" generated)
image_allowed("${fixture}" "${fixture}/../outside.png" escaped)
if(NOT valid OR generated OR escaped)
  message(FATAL_ERROR "Repository-relative image path counterexamples failed")
endif()
set(checked 0)
foreach(region IN LISTS regions)
  file(READ "${region}" data)
  string(JSON name ERROR_VARIABLE absent GET "${data}" tileset)
  if(absent)
    continue()
  endif()
  set(file "${root}/assets/tilesets/${name}.json")
  get_filename_component(base "${file}" DIRECTORY)
  file(READ "${file}" tileset)
  string(JSON image GET "${tileset}" image)
  check_image("${base}/${image}")
  string(JSON count ERROR_VARIABLE absent LENGTH "${tileset}" sampling)
  if(NOT absent AND count GREATER 0)
    math(EXPR last "${count}-1")
    foreach(i RANGE 0 ${last})
      string(JSON role MEMBER "${tileset}" sampling ${i})
      string(JSON mode GET "${tileset}" sampling "${role}" mode)
      if(mode STREQUAL "assembled")
        continue() # Assembled corners have no image to approve.
      endif()
      string(JSON image GET "${tileset}" sampling "${role}" image)
      check_image("${base}/${image}")
      file(REAL_PATH "${base}/${image}" inner)
      if(inner MATCHES "/runtime/trials/")
        message(FATAL_ERROR "Default tileset references trial runtime: ${inner}")
      endif()
      set(found FALSE)
      foreach(manifest IN LISTS manifests)
        file(READ "${manifest}" pipeline)
        get_filename_component(pipeline_base "${manifest}" DIRECTORY)
        string(JSON candidates LENGTH "${pipeline}" candidates)
        math(EXPR final "${candidates}-1")
        foreach(c RANGE 0 ${final})
          string(JSON approved ERROR_VARIABLE absent GET "${pipeline}" candidates ${c} approved_runtime_candidate)
          if(absent OR NOT approved)
            continue()
          endif()
          string(JSON approval_type TYPE "${pipeline}" candidates ${c} approved_runtime_candidate)
          if(NOT approval_type STREQUAL "BOOLEAN")
            message(FATAL_ERROR "Approval must be a boolean: ${manifest}")
          endif()
          string(JSON runtime GET "${pipeline}" candidates ${c} runtime_file)
          file(REAL_PATH "${pipeline_base}/${runtime}" candidate_image)
          if(NOT candidate_image STREQUAL inner)
            continue()
          endif()
          string(REGEX REPLACE "[.]png$" ".provenance.json" record_file "${inner}")
          file(READ "${record_file}" record)
          string(JSON id GET "${pipeline}" candidates ${c} id)
          string(JSON recorded_id GET "${record}" candidate)
          string(JSON recorded_runtime GET "${record}" runtime_file)
          string(JSON expected_hash GET "${record}" runtime_sha256)
          file(SHA256 "${inner}" actual_hash)
          if(NOT id STREQUAL recorded_id OR NOT runtime STREQUAL recorded_runtime OR NOT actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Approved runtime provenance mismatch: ${inner}")
          endif()
          set(found TRUE)
        endforeach()
      endforeach()
      if(NOT found)
        message(FATAL_ERROR "Default sampling image has no manifest approval: ${inner}")
      endif()
    endforeach()
  endif()
  math(EXPR checked "${checked}+1")
  message(STATUS "Approved default checked: ${region} -> ${name}")
endforeach()
message(STATUS "DEFAULT TILESET CHECKS PASS: ${checked} tilesets across all region files")

# Explicit trial references must resolve to their own trial record and manifest opt-in.
file(GLOB tilesets "${root}/assets/tilesets/*.json")
foreach(file IN LISTS tilesets)
  file(READ "${file}" data)
  get_filename_component(base "${file}" DIRECTORY)
  string(JSON count ERROR_VARIABLE absent LENGTH "${data}" sampling)
  if(absent OR count EQUAL 0)
    continue()
  endif()
  math(EXPR last "${count}-1")
  foreach(i RANGE 0 ${last})
    string(JSON role MEMBER "${data}" sampling ${i})
    string(JSON mode GET "${data}" sampling "${role}" mode)
    if(mode STREQUAL "assembled")
      continue() # No image exists; parser validates perpendicular exposures.
    endif()
    string(JSON image GET "${data}" sampling "${role}" image)
    file(REAL_PATH "${base}/${image}" image)
    if(NOT image MATCHES "/runtime/trials/")
      continue()
    endif()
    check_image("${image}")
    string(REGEX REPLACE "[.]png$" ".provenance.json" sidecar "${image}")
    file(READ "${sidecar}" record)
    string(JSON status GET "${record}" status)
    string(JSON hash GET "${record}" runtime_sha256)
    string(JSON candidate GET "${record}" candidate)
    string(JSON manifest_path GET "${record}" manifest_path)
    string(JSON recorded_file GET "${record}" runtime_file)
    file(SHA256 "${image}" actual)
    if(NOT status STREQUAL "trial" OR NOT hash STREQUAL actual)
      message(FATAL_ERROR "Trial provenance mismatch: ${image}")
    endif()
    file(READ "${root}/${manifest_path}" pipeline)
    get_filename_component(pipeline_base "${root}/${manifest_path}" DIRECTORY)
    string(JSON count LENGTH "${pipeline}" candidates)
    math(EXPR end "${count}-1")
    set(found FALSE)
    foreach(c RANGE 0 ${end})
      string(JSON id GET "${pipeline}" candidates ${c} id)
      if(NOT id STREQUAL candidate)
        continue()
      endif()
      string(JSON enabled GET "${pipeline}" candidates ${c} trial_runtime_candidate)
      string(JSON type TYPE "${pipeline}" candidates ${c} trial_runtime_candidate)
      string(JSON runtime GET "${pipeline}" candidates ${c} trial_runtime_file)
      file(REAL_PATH "${pipeline_base}/${runtime}" resolved)
      if(enabled AND type STREQUAL "BOOLEAN" AND resolved STREQUAL image AND runtime STREQUAL recorded_file)
        set(found TRUE)
      endif()
    endforeach()
    if(NOT found)
      message(FATAL_ERROR "Trial image not opted in by manifest: ${image}")
    endif()
  endforeach()
endforeach()
