cmake_minimum_required(VERSION 3.28)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
execute_process(COMMAND "${EXE}" --help RESULT_VARIABLE code OUTPUT_VARIABLE help ERROR_VARIABLE error TIMEOUT 10)
if(NOT code EQUAL 0)
 message(FATAL_ERROR "Help failed: ${code}: ${error}")
endif()
file(READ "${root}/docs/runtime-options.md" docs)
foreach(text IN ITEMS help docs)
 string(REGEX MATCHALL "--[a-z][a-z-]*" ${text}_options "${${text}}")
 list(REMOVE_DUPLICATES ${text}_options)
 list(SORT ${text}_options)
endforeach()
set(expected --debug-hud --decorations --help --tileset --vsync)
if(NOT help_options STREQUAL docs_options OR NOT help_options STREQUAL expected)
 message(FATAL_ERROR "Help/docs options disagree: ${help_options} / ${docs_options}")
endif()
execute_process(COMMAND "${EXE}" --invalid RESULT_VARIABLE invalid ERROR_VARIABLE message TIMEOUT 10)
if(invalid EQUAL 0 OR NOT message MATCHES "Unknown option")
 message(FATAL_ERROR "Invalid option did not fail before window creation")
endif()
message(STATUS "HELP PASS: exit 0, all options match documentation\n${help}")
