cmake_minimum_required(VERSION 3.28)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(READ "${root}/tools/inner_macro_capture.json" plan)
string(JSON count LENGTH "${plan}" trials)
math(EXPR last "${count}-1")
include("${CMAKE_CURRENT_LIST_DIR}/TilesetImageChecks.cmake")
string(JSON region GET "${plan}" region)
file(READ "${root}/assets/regions/${region}.json" region_data)
string(JSON default_tileset GET "${region_data}" tileset)
set(default_count 0)
foreach(i RANGE 0 ${last})
  string(JSON tileset GET "${plan}" trials ${i} tileset)
  if(tileset STREQUAL "")
    math(EXPR default_count "${default_count}+1")
    string(JSON extra GET "${plan}" trials ${i})
    set(tileset "${default_tileset}")
  endif()
  check_tileset_images("${root}/assets/tilesets/${tileset}.json")
endforeach()
if(NOT default_count EQUAL 1)
  message(FATAL_ERROR "Capture plan must have exactly one region-default trial to duplicate")
endif()
# A new trial identity exists only in build data; capture and validation both discover it.
string(JSON extra SET "${extra}" id "\"temporary_data_only\"")
string(JSON plan SET "${plan}" trials ${count} "${extra}")
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run)
set(work "${root}/build/macro_capture_checks/${run}")
file(MAKE_DIRECTORY "${work}")
file(WRITE "${work}/plan.json" "${plan}\n")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DCONFIG=${work}/plan.json" "-DBIN=${BIN}"
  "-DOUT=${work}/captures" -P "${root}/tools/inner_macro_capture.cmake" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Data-only additional trial failed: ${code}")
endif()
message(STATUS "DATA-ONLY TRIAL PASS: ${work}")
