# Manual offline validation; excluded from the seven runtime CTest cases.
# cmake -DPIPELINE_EXE=D:/project-slit/build/Release/tile_pipeline.exe -P tests/TilePipelineChecks.cmake
cmake_minimum_required(VERSION 3.28)
if(NOT DEFINED PIPELINE_EXE)
    message(FATAL_ERROR "Pass -DPIPELINE_EXE=<tile_pipeline executable>")
endif()
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(asset "${root}/assets/tiles/avatar_lake")
set(manifest "${asset}/avatar_lake.pipeline.manifest.json")
# A fresh directory per validation preserves all previous checks and experiments.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run)
set(checks "${root}/build/tile_pipeline_checks/${run}")
file(MAKE_DIRECTORY "${checks}/configs")
set(out "${checks}/generated")
function(invoke manifest_path output_path expected_error)
    execute_process(COMMAND "${PIPELINE_EXE}" "${manifest_path}" "${output_path}"
        RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(expected_error STREQUAL "")
        if(NOT code EQUAL 0)
            message(FATAL_ERROR "Unexpected failure ${code}: ${stdout}\n${stderr}")
        endif()
    else()
        if(code EQUAL 0 OR NOT stderr MATCHES "${expected_error}")
            message(FATAL_ERROR "Expected '${expected_error}', got ${code}: ${stdout}\n${stderr}")
        endif()
    endif()
    message(STATUS "exit=${code} ${stdout}${stderr}")
endfunction()
invoke("${manifest}" "${out}" "")
file(READ "${out}/report.json" report)
foreach(i RANGE 0 2)
    string(JSON different GET "${report}" candidates ${i} different_rgba_pixels)
    if(NOT different EQUAL 0)
        message(FATAL_ERROR "Reference mismatch candidate ${i}: ${different}")
    endif()
endforeach()
string(JSON h GET "${report}" candidates 1 edge_h)
string(JSON v GET "${report}" candidates 1 edge_v)
if(h LESS 21.045 OR h GREATER_EQUAL 21.055 OR v LESS 22.225 OR v GREATER_EQUAL 22.235)
    message(FATAL_ERROR "Unexpected E1 seams: ${h}, ${v}")
endif()
file(GLOB outputs "${out}/*")
list(LENGTH outputs count)
string(JSON candidate_count LENGTH "${report}" manifest candidates)
math(EXPR expected_count "${candidate_count} * 4 + 1")
if(NOT count EQUAL expected_count)
    message(FATAL_ERROR "Expected ${expected_count} manifest-driven candidate outputs, got ${count}")
endif()
foreach(path IN LISTS outputs)
    file(SHA256 "${path}" before)
    string(APPEND hashes "${path}:${before}\n")
endforeach()
invoke("${manifest}" "${out}" "")
foreach(path IN LISTS outputs)
    file(SHA256 "${path}" after)
    string(APPEND hashes_after "${path}:${after}\n")
endforeach()
if(NOT hashes STREQUAL hashes_after)
    message(FATAL_ERROR "Second run changed output bytes")
endif()
# report.manifest is a reusable snapshot with absolute read paths.
string(JSON snapshot GET "${report}" manifest)
file(WRITE "${checks}/configs/restore.json" "${snapshot}")
invoke("${checks}/configs/restore.json" "${checks}/restored" "")
foreach(path IN LISTS outputs)
    get_filename_component(name "${path}" NAME)
    file(SHA256 "${checks}/restored/${name}" restored)
    file(SHA256 "${path}" original)
    if(NOT restored STREQUAL original)
        message(FATAL_ERROR "Snapshot restore differs: ${name}")
    endif()
endforeach()
string(JSON bad SET "${snapshot}" source expected_size "[1255,1254]")
file(WRITE "${checks}/configs/size.json" "${bad}")
invoke("${checks}/configs/size.json" "${checks}/bad-size" "Source size does not match")
string(JSON bad SET "${snapshot}" source path "\"${checks}/configs/missing.png\"")
file(WRITE "${checks}/configs/missing.json" "${bad}")
invoke("${checks}/configs/missing.json" "${checks}/bad-missing" "Cannot load source")
string(JSON bad SET "${snapshot}" candidates 0 crop "[1253,0,2,1254]")
file(WRITE "${checks}/configs/crop.json" "${bad}")
invoke("${checks}/configs/crop.json" "${checks}/bad-crop" "Crop outside source")
string(JSON bad SET "${snapshot}" candidates 0 output_size "[80.5,80]")
file(WRITE "${checks}/configs/type.json" "${bad}")
invoke("${checks}/configs/type.json" "${checks}/bad-type" "Expected integer")
invoke("${manifest}" "${asset}/source" "protected input/reference")
invoke("${manifest}" "${asset}/candidates/desktop-2026-09-13" "protected input/reference")
# Use the relocated manifest too, exercising source/reference protection independently.
invoke("${checks}/configs/restore.json" "${asset}/source" "protected input/reference")
invoke("${checks}/configs/restore.json" "${asset}/candidates/desktop-2026-09-13" "protected input/reference")
file(MAKE_DIRECTORY "${checks}/collision")
file(WRITE "${checks}/collision/E1_medium.png" "DO NOT OVERWRITE")
invoke("${manifest}" "${checks}/collision" "Refusing to overwrite")
file(READ "${checks}/collision/E1_medium.png" sentinel)
file(GLOB collision_files "${checks}/collision/*")
list(LENGTH collision_files collision_count)
if(NOT sentinel STREQUAL "DO NOT OVERWRITE" OR NOT collision_count EQUAL 1)
    message(FATAL_ERROR "Overwrite protection or preflight failed")
endif()
message(STATUS "TILE PIPELINE CHECKS PASS: ${checks}")
