function(image_allowed repository path result)
  file(REAL_PATH "${repository}" repository)
  file(REAL_PATH "${path}" resolved)
  file(RELATIVE_PATH relative "${repository}" "${resolved}")
  string(TOLOWER "${relative}" relative)
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "^[.][.](/|$)" OR
      relative MATCHES "^build(/|$)" OR NOT EXISTS "${resolved}" OR IS_DIRECTORY "${resolved}")
    set(${result} FALSE PARENT_SCOPE)
  else()
    set(${result} TRUE PARENT_SCOPE)
  endif()
endfunction()

function(check_image path)
  image_allowed("${root}" "${path}" allowed)
  if(NOT allowed)
    message(FATAL_ERROR "Tileset image must exist inside repository and outside its build directory: ${path}")
  endif()
endfunction()

function(check_tileset_images file)
  get_filename_component(base "${file}" DIRECTORY)
  file(READ "${file}" data)
  string(JSON image GET "${data}" image)
  file(REAL_PATH "${image}" image BASE_DIRECTORY "${base}")
  check_image("${image}")
  string(JSON count ERROR_VARIABLE absent LENGTH "${data}" sampling)
  if(NOT absent AND count GREATER 0)
    math(EXPR last "${count}-1")
    foreach(i RANGE 0 ${last})
      string(JSON role MEMBER "${data}" sampling ${i})
      string(JSON image GET "${data}" sampling "${role}" image)
      file(REAL_PATH "${image}" image BASE_DIRECTORY "${base}")
      check_image("${image}")
    endforeach()
  endif()
endfunction()
