cmake_minimum_required(VERSION 3.28)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT EXISTS "${PIPELINE_EXE}")
  message(FATAL_ERROR "Build tile_pipeline before running the export checks")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run)
set(work "${root}/build/tile_export_checks/${run}")
file(MAKE_DIRECTORY "${work}/config")
set(asset "${root}/assets/tiles/avatar_lake")
file(READ "${asset}/avatar_lake.pipeline.manifest.json" data)
string(JSON source GET "${data}" source path)
string(JSON data SET "${data}" source path "\"${asset}/${source}\"")
string(JSON count LENGTH "${data}" candidates)
math(EXPR last "${count}-1")
foreach(i RANGE 0 ${last})
  string(JSON ref ERROR_VARIABLE absent GET "${data}" candidates ${i} reference)
  if(NOT absent)
    string(JSON data SET "${data}" candidates ${i} reference "\"${asset}/${ref}\"")
  endif()
  string(JSON approved ERROR_VARIABLE absent GET "${data}" candidates ${i} approved_runtime_candidate)
  if(NOT absent AND approved)
    set(selected ${i})
    string(JSON candidate GET "${data}" candidates ${i} id)
    string(JSON relative GET "${data}" candidates ${i} runtime_file)
  endif()
endforeach()
if(NOT DEFINED selected)
  message(FATAL_ERROR "No approved candidate in test data")
endif()
set(manifest "${work}/config/manifest.json")
file(WRITE "${manifest}" "${data}")
execute_process(COMMAND "${PIPELINE_EXE}" "${manifest}" "${work}/generated" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Fixture generation failed")
endif()
set(input "${work}/generated/${candidate}.png")
set(destination "${work}/config/${relative}")
string(REGEX REPLACE "[.]png$" ".provenance.json" record "${destination}")
function(export_check expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DPIPELINE_EXE=${PIPELINE_EXE}" ${ARGN}
    -P "${root}/tools/export_tile.cmake" RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(expected STREQUAL "")
    if(NOT code EQUAL 0)
      message(FATAL_ERROR "Export failed: ${code}\n${out}\n${err}")
    endif()
  elseif(code EQUAL 0 OR NOT err MATCHES "${expected}")
    message(FATAL_ERROR "Expected ${expected}: ${code}\n${out}\n${err}")
  endif()
endfunction()
set(args "-DMANIFEST=${manifest}" "-DCANDIDATE=${candidate}" "-DINPUT=${input}")
export_check("" ${args})
file(SHA256 "${destination}" original_hash)
file(SHA256 "${record}" original_record_hash)
export_check("" ${args})
file(SHA256 "${record}" repeated_hash)
if(NOT original_record_hash STREQUAL repeated_hash)
  message(FATAL_ERROR "Idempotent export changed provenance")
endif()
# Restore uses only its saved manifest, even after the live manifest is removed.
file(RENAME "${manifest}" "${manifest}.saved")
file(RENAME "${destination}" "${work}/saved.png")
export_check("" "-DRECORD=${record}")
file(SHA256 "${destination}" restored_hash)
if(NOT restored_hash STREQUAL original_hash)
  message(FATAL_ERROR "Recorded snapshot restoration differs")
endif()
file(WRITE "${manifest}" "${data}")
export_check("Input differs" "-DMANIFEST=${manifest}" "-DCANDIDATE=${candidate}"
  "-DINPUT=${asset}/${source}")
string(JSON denied SET "${data}" candidates ${selected} approved_runtime_candidate false)
file(WRITE "${manifest}" "${denied}")
export_check("not approved" ${args})
file(WRITE "${manifest}" "${data}")
file(RENAME "${destination}" "${work}/restored.png")
file(WRITE "${destination}" "DO NOT OVERWRITE")
export_check("Refusing to overwrite" ${args})
file(READ "${destination}" sentinel)
if(NOT sentinel STREQUAL "DO NOT OVERWRITE")
  message(FATAL_ERROR "Conflicting file overwritten")
endif()
message(STATUS "EXPORT CHECKS PASS: ${work}")

# Schema-2 trial uses the same contract without granting approved-runtime access.
file(READ "${asset}/avatar_lake_top.pipeline.manifest.json" top)
string(JSON source GET "${top}" source path)
string(JSON top SET "${top}" source path "\"${asset}/${source}\"")
string(JSON inner GET "${top}" previews inner)
string(JSON top SET "${top}" previews inner "\"${asset}/${inner}\"")
string(JSON count LENGTH "${top}" candidates)
math(EXPR last "${count}-1")
foreach(i RANGE 0 ${last})
  string(JSON enabled ERROR_VARIABLE absent GET "${top}" candidates ${i} trial_runtime_candidate)
  if(NOT absent AND enabled)
    set(selected ${i})
    string(JSON candidate GET "${top}" candidates ${i} id)
    string(JSON relative GET "${top}" candidates ${i} trial_runtime_file)
  endif()
endforeach()
set(manifest "${work}/config/top.json")
file(WRITE "${manifest}" "${top}")
get_filename_component(bin "${PIPELINE_EXE}" DIRECTORY)
execute_process(COMMAND "${bin}/top_pipeline.exe" "${manifest}" "${work}/top-generated" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Top fixture generation failed")
endif()
set(args -DTRIAL=ON "-DMANIFEST=${manifest}" "-DCANDIDATE=${candidate}" "-DINPUT=${work}/top-generated/${candidate}.png")
export_check("" ${args})
set(destination "${work}/config/${relative}")
string(REGEX REPLACE "[.]png$" ".provenance.json" record "${destination}")
file(SHA256 "${record}" initial_record)
file(SHA256 "${destination}" initial_png)
export_check("" ${args})
file(SHA256 "${record}" repeat_record)
if(NOT repeat_record STREQUAL initial_record)
  message(FATAL_ERROR "Trial provenance changed on re-export")
endif()
file(RENAME "${destination}" "${work}/trial-saved.png")
export_check("" "-DRECORD=${record}")
file(SHA256 "${destination}" restored)
if(NOT restored STREQUAL initial_png)
  message(FATAL_ERROR "Trial restore changed output")
endif()
export_check("not approved" -DTRIAL=OFF "-DMANIFEST=${manifest}" "-DCANDIDATE=${candidate}" "-DINPUT=${work}/top-generated/${candidate}.png")
string(JSON bad SET "${top}" candidates ${selected} trial_runtime_file "\"runtime/escape.png\"")
file(WRITE "${manifest}" "${bad}")
export_check("runtime_file" ${args})
string(JSON bad SET "${top}" candidates ${selected} approved_runtime_candidate true)
string(JSON bad SET "${bad}" candidates ${selected} runtime_file "\"${relative}\"")
file(WRITE "${manifest}" "${bad}")
export_check("runtime_file" -DTRIAL=OFF "-DMANIFEST=${manifest}" "-DCANDIDATE=${candidate}" "-DINPUT=${work}/top-generated/${candidate}.png")
file(WRITE "${manifest}" "${top}")
export_check("Input differs" -DTRIAL=ON "-DMANIFEST=${manifest}" "-DCANDIDATE=${candidate}" "-DINPUT=${asset}/${source}")
file(RENAME "${destination}" "${work}/trial-restored.png")
file(WRITE "${destination}" "DO NOT OVERWRITE")
export_check("Refusing to overwrite" ${args})
message(STATUS "TRIAL EXPORT CHECKS PASS: schema dispatch, snapshot restore, mode isolation and exclusive publication")
