cmake_minimum_required(VERSION 3.28)
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(asset "${root}/assets/tiles/avatar_lake")
set(manifest "${asset}/avatar_lake_top.pipeline.manifest.json")
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run)
set(work "${root}/build/top_pipeline_checks/${run}")
file(MAKE_DIRECTORY "${work}/config")
function(invoke input output error)
  execute_process(COMMAND "${TOP_EXE}" "${input}" "${output}" RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(error STREQUAL "")
    if(NOT code EQUAL 0)
      message(FATAL_ERROR "Top pipeline failed: ${code}\n${stdout}\n${stderr}")
    endif()
  elseif(code EQUAL 0 OR NOT stderr MATCHES "${error}")
    message(FATAL_ERROR "Expected '${error}': ${code}\n${stdout}\n${stderr}")
  endif()
  message(STATUS "${stdout}${stderr}")
endfunction()
file(READ "${manifest}" data)
string(JSON source GET "${data}" source path)
file(SHA256 "${asset}/${source}" source_before)
invoke("${manifest}" "${work}/generated" "")
file(GLOB outputs "${work}/generated/*")
foreach(path IN LISTS outputs)
  file(SHA256 "${path}" hash)
  string(APPEND before "${path}:${hash}\n")
endforeach()
invoke("${manifest}" "${work}/generated" "")
foreach(path IN LISTS outputs)
  file(SHA256 "${path}" hash)
  string(APPEND after "${path}:${hash}\n")
endforeach()
if(NOT before STREQUAL after)
  message(FATAL_ERROR "Top regeneration is not byte identical")
endif()
file(SHA256 "${asset}/${source}" source_after)
if(NOT source_before STREQUAL source_after)
  message(FATAL_ERROR "Source changed")
endif()
file(WRITE "${work}/reproduction.json" "{\"all_output_sha256_identical\":true,\"source_before\":\"${source_before}\",\"source_after\":\"${source_after}\"}\n")
# Relocation exercises source/runtime protection independently of manifest-directory protection.
string(JSON data SET "${data}" source path "\"${asset}/${source}\"")
string(JSON inner GET "${data}" previews inner)
string(JSON data SET "${data}" previews inner "\"${asset}/${inner}\"")
file(WRITE "${work}/config/relocated.json" "${data}")
# Compare every legacy candidate PNG, including its previews, against the preserved run.
# A clean checkout instead executes the explicitly fringe-free candidate set twice.
if(NOT DEFINED TOP_BASELINE)
  set(TOP_BASELINE "${root}/build/tile_pipeline/avatar_lake_top_raw_01_20260914")
endif()
set(plain "${data}")
string(JSON plain SET "${plain}" candidates "[]")
string(JSON plain SET "${plain}" comparisons "[]")
string(JSON length LENGTH "${data}" candidates)
math(EXPR last "${length}-1")
set(plain_count 0)
set(legacy_ids)
foreach(i RANGE 0 ${last})
  string(JSON entry GET "${data}" candidates ${i})
  string(JSON fringe ERROR_VARIABLE absent GET "${entry}" fringe)
  if(absent)
    string(JSON id GET "${entry}" id)
    list(APPEND legacy_ids "${id}")
    string(JSON plain SET "${plain}" candidates ${plain_count} "${entry}")
    math(EXPR plain_count "${plain_count}+1")
  endif()
endforeach()
if(EXISTS "${TOP_BASELINE}")
  set(reference "${TOP_BASELINE}")
  set(actual "${work}/generated")
  message(STATUS "Legacy PNG verification: preserved TOP-NORM baseline")
else()
  file(WRITE "${work}/config/no-fringe.json" "${plain}")
  invoke("${work}/config/no-fringe.json" "${work}/no-fringe-first" "")
  invoke("${work}/config/no-fringe.json" "${work}/no-fringe-second" "")
  set(reference "${work}/no-fringe-first")
  set(actual "${work}/no-fringe-second")
  message(STATUS "Legacy PNG verification: clean environment, two fringe-free generations")
endif()
foreach(id IN LISTS legacy_ids)
  file(GLOB legacy "${reference}/${id}.png" "${reference}/${id}_*.png")
  if(NOT legacy)
    message(FATAL_ERROR "No legacy PNGs for ${id}")
  endif()
  foreach(path IN LISTS legacy)
    get_filename_component(name "${path}" NAME)
    file(SHA256 "${path}" expected)
    file(SHA256 "${actual}/${name}" observed)
    file(SHA256 "${work}/generated/${name}" generated)
    if(NOT expected STREQUAL observed OR NOT expected STREQUAL generated)
      message(FATAL_ERROR "Legacy PNG changed: ${name}")
    endif()
  endforeach()
endforeach()
message(STATUS "Legacy PNGs identical; complete regeneration also checks fringe determinism")
string(JSON bad SET "${data}" source expected_sha256 "\"wrong\"")
file(WRITE "${work}/config/hash.json" "${bad}")
invoke("${work}/config/hash.json" "${work}/bad-hash" "Source SHA256 mismatch before image load")
if(EXISTS "${work}/bad-hash")
  message(FATAL_ERROR "Rejected source produced an output directory")
endif()
foreach(protected IN ITEMS "${asset}" "${asset}/source" "${asset}/runtime" "${asset}/candidates" "${work}/config")
  invoke("${work}/config/relocated.json" "${protected}" "[Pp]rotected")
endforeach()
file(MAKE_DIRECTORY "${work}/conflict")
file(WRITE "${work}/conflict/report.json" "DO NOT OVERWRITE")
invoke("${manifest}" "${work}/conflict" "Refusing to overwrite")
file(GLOB conflict "${work}/conflict/*")
list(LENGTH conflict count)
file(READ "${work}/conflict/report.json" sentinel)
if(NOT count EQUAL 1 OR NOT sentinel STREQUAL "DO NOT OVERWRITE")
  message(FATAL_ERROR "Full-output preflight failed")
endif()
execute_process(COMMAND "${TOP_EXE}" --self-test "${manifest}" RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Synthetic validation checks failed: ${stdout}\n${stderr}")
endif()
message(STATUS "${stdout}TOP PIPELINE CHECKS PASS: ${work}")
# Direction-aware side generation: deterministic bytes and synthetic column/seam failures.
set(side "${asset}/avatar_lake_side.pipeline.manifest.json")
file(READ "${side}" side_data)
string(JSON side_source GET "${side_data}" source path)
file(SHA256 "${asset}/${side_source}" side_before)
invoke("${side}" "${work}/side-first" "")
invoke("${side}" "${work}/side-second" "")
file(GLOB side_outputs "${work}/side-first/*")
foreach(path IN LISTS side_outputs)
  get_filename_component(name "${path}" NAME)
  file(SHA256 "${path}" a)
  file(SHA256 "${work}/side-second/${name}" b)
  if(NOT a STREQUAL b)
    message(FATAL_ERROR "Side regeneration differs: ${name}")
  endif()
endforeach()
file(SHA256 "${asset}/${side_source}" side_after)
if(NOT side_before STREQUAL side_after)
  message(FATAL_ERROR "Side source changed")
endif()
execute_process(COMMAND "${TOP_EXE}" --self-test "${side}" RESULT_VARIABLE code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Side synthetic validation failed: ${stdout}\n${stderr}")
endif()
message(STATUS "${stdout}SIDE CHECKS PASS: byte reproduction, immutable source, vertical seam and column opacity")
# Approved-inner derivation: synthetic source, exact reproduction, hash rejection and data controls.
set(derived "${asset}/avatar_lake_side_crevice.pipeline.manifest.json")
execute_process(COMMAND "${TOP_EXE}" --derived-fixture "${derived}" "${work}/derived-config" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Derived fixture failed")
endif()
set(fixture "${work}/derived-config/manifest.json")
invoke("${fixture}" "${work}/derived-first" "")
invoke("${fixture}" "${work}/derived-second" "")
foreach(name IN ITEMS crevice_v1.png report.json)
  file(SHA256 "${work}/derived-first/${name}" a)
  file(SHA256 "${work}/derived-second/${name}" b)
  if(NOT a STREQUAL b)
    message(FATAL_ERROR "Derived reproduction differs: ${name}")
  endif()
endforeach()
file(READ "${fixture}" derived_data)
string(JSON invalid SET "${derived_data}" source expected_sha256 "\"wrong\"")
file(WRITE "${work}/derived-config/wrong.json" "${invalid}")
invoke("${work}/derived-config/wrong.json" "${work}/derived-rejected" "Source SHA256 mismatch before image load")
if(EXISTS "${work}/derived-rejected")
  message(FATAL_ERROR "Derived hash rejection wrote output")
endif()
file(SHA256 "${work}/derived-first/crevice_v1.png" original_hash)
foreach(field IN ITEMS crevice_threshold full_columns luminance_weights hash)
  if(field STREQUAL "crevice_threshold")
    set(value 0)
  elseif(field STREQUAL "full_columns")
    set(value 10)
  elseif(field STREQUAL "luminance_weights")
    set(value "[0,0,0]")
  else()
    set(value "{\"y_multiplier\":1,\"x_multiplier\":1,\"mask\":1023,\"range\":1024}")
  endif()
  string(JSON changed SET "${derived_data}" derivation ${field} "${value}")
  file(WRITE "${work}/derived-config/${field}.json" "${changed}")
  invoke("${work}/derived-config/${field}.json" "${work}/derived-${field}" "")
  file(SHA256 "${work}/derived-${field}/crevice_v1.png" changed_hash)
  if(original_hash STREQUAL changed_hash)
    message(FATAL_ERROR "Derived setting ignored: ${field}")
  endif()
endforeach()
message(STATUS "DERIVED CHECKS PASS: synthetic reproduction, hash refusal, weights/threshold/full columns/hash controls")
