cmake_minimum_required(VERSION 3.28)
# Export: -DMANIFEST=... -DCANDIDATE=... -DINPUT=... -P tools/export_tile.cmake
# Restore: -DRECORD=... -P tools/export_tile.cmake (immutable source still required).
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED PIPELINE_EXE)
  set(PIPELINE_EXE "${ROOT}/build/Release/tile_pipeline.exe")
endif()
if(DEFINED RECORD)
  file(READ "${RECORD}" record)
  string(JSON original GET "${record}" manifest)
  string(JSON manifest_relative GET "${record}" manifest_path)
  string(JSON CANDIDATE GET "${record}" candidate)
  set(MANIFEST "${ROOT}/${manifest_relative}")
else()
  if(NOT DEFINED MANIFEST OR NOT DEFINED CANDIDATE OR NOT DEFINED INPUT)
    message(FATAL_ERROR "Export requires MANIFEST, CANDIDATE and INPUT; restore requires RECORD")
  endif()
  file(READ "${MANIFEST}" original)
  file(RELATIVE_PATH manifest_relative "${ROOT}" "${MANIFEST}")
endif()
string(JSON schema GET "${original}" schema)
set(GENERATOR_EXE "${PIPELINE_EXE}")
if(schema EQUAL 2)
  get_filename_component(bin "${PIPELINE_EXE}" DIRECTORY)
  set(GENERATOR_EXE "${bin}/top_pipeline.exe")
endif()
if(DEFINED RECORD)
  string(JSON status ERROR_VARIABLE absent GET "${record}" status)
  if(NOT absent AND status STREQUAL "trial")
    set(TRIAL TRUE)
  endif()
endif()
get_filename_component(base "${MANIFEST}" DIRECTORY)
string(JSON count LENGTH "${original}" candidates)
math(EXPR last "${count}-1")
set(selected -1)
foreach(i RANGE 0 ${last})
  string(JSON id GET "${original}" candidates ${i} id)
  if(id STREQUAL CANDIDATE)
    set(selected ${i})
  endif()
endforeach()
if(selected LESS 0)
  message(FATAL_ERROR "Unknown candidate: ${CANDIDATE}")
endif()
set(flag approved_runtime_candidate)
set(file_field runtime_file)
if(TRIAL)
  set(flag trial_runtime_candidate)
  set(file_field trial_runtime_file)
endif()
string(JSON approved ERROR_VARIABLE error GET "${original}" candidates ${selected} ${flag})
string(JSON approval_type ERROR_VARIABLE type_error TYPE "${original}" candidates ${selected} ${flag})
if(error OR type_error OR NOT approval_type STREQUAL "BOOLEAN" OR NOT approved)
  message(FATAL_ERROR "Candidate is not approved for runtime export")
endif()
string(JSON relative GET "${original}" candidates ${selected} ${file_field})
set(pattern "^runtime/[A-Za-z0-9_-]+[.]png$")
if(TRIAL)
  set(pattern "^runtime/trials/[A-Za-z0-9_-]+[.]png$")
endif()
if(NOT relative MATCHES "${pattern}")
  message(FATAL_ERROR "runtime_file must be a PNG basename in runtime/")
endif()
file(REAL_PATH "${base}/runtime" runtime)
cmake_path(NORMAL_PATH base OUTPUT_VARIABLE normalized_base)
if(NOT runtime STREQUAL "${normalized_base}/runtime")
  message(FATAL_ERROR "Runtime directory must not redirect through a link")
endif()
if(TRIAL)
  file(REAL_PATH "${base}/runtime/trials" trial_directory)
  if(NOT trial_directory STREQUAL "${normalized_base}/runtime/trials")
    message(FATAL_ERROR "Trial directory must not redirect through a link")
  endif()
endif()
set(destination "${base}/${relative}")
string(REGEX REPLACE "[.]png$" ".provenance.json" sidecar "${destination}")
set(snapshot "${original}")
string(JSON source_relative GET "${original}" source path)
if(IS_ABSOLUTE "${source_relative}")
  file(REAL_PATH "${source_relative}" source)
else()
  file(REAL_PATH "${base}/${source_relative}" source)
endif()
file(SHA256 "${source}" source_hash)
if(DEFINED RECORD)
  string(JSON expected_source GET "${record}" source_sha256)
  if(NOT expected_source STREQUAL source_hash)
    message(FATAL_ERROR "Source hash mismatch; restore refuses changed source")
  endif()
endif()
string(JSON snapshot SET "${snapshot}" source path "\"${source}\"")
if(schema EQUAL 2)
  string(JSON inner GET "${snapshot}" previews inner)
  if(IS_ABSOLUTE "${inner}")
    file(REAL_PATH "${inner}" inner)
  else()
    file(REAL_PATH "${base}/${inner}" inner)
  endif()
  string(JSON snapshot SET "${snapshot}" previews inner "\"${inner}\"")
endif()
foreach(i RANGE 0 ${last})
  string(JSON ref ERROR_VARIABLE absent GET "${snapshot}" candidates ${i} reference)
  if(NOT absent)
    if(IS_ABSOLUTE "${ref}")
      file(REAL_PATH "${ref}" ref)
    else()
      file(REAL_PATH "${base}/${ref}" ref)
    endif()
    string(JSON snapshot SET "${snapshot}" candidates ${i} reference "\"${ref}\"")
  endif()
endforeach()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run)
set(work "${ROOT}/build/tile_exports/${run}")
file(MAKE_DIRECTORY "${work}/config")
file(WRITE "${work}/config/manifest.json" "${snapshot}\n")
execute_process(COMMAND "${GENERATOR_EXE}" "${work}/config/manifest.json" "${work}/generated" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Regeneration failed: ${code}")
endif()
file(SHA256 "${source}" after_source)
if(NOT after_source STREQUAL source_hash)
  message(FATAL_ERROR "Source changed during regeneration")
endif()
set(generated "${work}/generated/${CANDIDATE}.png")
file(READ "${work}/generated/report.json" generated_report)
if(schema EQUAL 2)
  string(JSON classification GET "${generated_report}" candidates ${selected} status)
  if(classification STREQUAL "FAIL")
    message(FATAL_ERROR "Technical FAIL cannot be exported")
  endif()
endif()
file(SHA256 "${generated}" output_hash)
if(DEFINED RECORD)
  string(JSON expected_output GET "${record}" runtime_sha256)
  if(NOT output_hash STREQUAL expected_output)
    message(FATAL_ERROR "Restored output hash differs from export record")
  endif()
else()
  execute_process(COMMAND "${PIPELINE_EXE}" --compare-images "${generated}" "${INPUT}" RESULT_VARIABLE code)
  if(NOT code EQUAL 0)
    message(FATAL_ERROR "Input differs from regenerated candidate; export refused")
  endif()
  set(record "{}")
  string(JSON record SET "${record}" schema 1)
  string(JSON record SET "${record}" candidate "\"${CANDIDATE}\"")
  string(JSON record SET "${record}" manifest_path "\"${manifest_relative}\"")
  string(JSON record SET "${record}" manifest "${original}")
  string(JSON record SET "${record}" source_sha256 "\"${source_hash}\"")
  string(JSON record SET "${record}" runtime_sha256 "\"${output_hash}\"")
  string(JSON record SET "${record}" runtime_file "\"${relative}\"")
  if(schema EQUAL 2)
    string(JSON palette GET "${generated_report}" candidates ${selected} palette_rgb)
    string(JSON record SET "${record}" classification "\"${classification}\"")
  else()
    string(JSON palette GET "${generated_report}" palette_rgb)
  endif()
  if(TRIAL)
    string(JSON record SET "${record}" status "\"trial\"")
  endif()
  string(JSON record SET "${record}" palette_rgb "${palette}")
endif()
string(JSON record GET "${record}")
file(WRITE "${work}/record.json" "${record}\n")
# Preflight both files before publishing either. Existing bytes are never rewritten.
foreach(pair IN ITEMS "${generated}|${destination}" "${work}/record.json|${sidecar}")
  string(REPLACE "|" ";" pair "${pair}")
  list(GET pair 0 from)
  list(GET pair 1 to)
  if(IS_SYMLINK "${to}")
    message(FATAL_ERROR "Output symlink refused: ${to}")
  endif()
  if(EXISTS "${to}")
    file(SHA256 "${from}" expected)
    file(SHA256 "${to}" actual)
    if(NOT expected STREQUAL actual)
      message(FATAL_ERROR "Refusing to overwrite different existing content: ${to}")
    endif()
  endif()
endforeach()
file(MAKE_DIRECTORY "${runtime}")
if(TRIAL)
  file(MAKE_DIRECTORY "${runtime}/trials")
endif()
set(copy_mode --copy-new)
if(TRIAL)
  set(copy_mode --copy-new-trial)
endif()
foreach(pair IN ITEMS "${generated}|${destination}" "${work}/record.json|${sidecar}")
  string(REPLACE "|" ";" pair "${pair}")
  list(GET pair 0 from)
  list(GET pair 1 to)
  if(NOT EXISTS "${to}")
    execute_process(COMMAND "${PIPELINE_EXE}" ${copy_mode} "${from}" "${to}" RESULT_VARIABLE code)
    if(NOT code EQUAL 0)
      message(FATAL_ERROR "Exclusive export failed: ${to}")
    endif()
  endif()
endforeach()
message(STATUS "EXPORTED ${CANDIDATE}: ${destination} SHA256=${output_hash}")
