cmake_minimum_required(VERSION 3.28)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED CONFIG)
  set(CONFIG "${CMAKE_CURRENT_LIST_DIR}/inner_macro_capture.json")
endif()
if(NOT DEFINED BIN)
  set(BIN "${ROOT}/build/Release")
endif()
if(NOT DEFINED OUT)
  string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef run)
  set(OUT "${ROOT}/build/preview/inner_macro_trial/${run}")
endif()
if(EXISTS "${OUT}")
  message(FATAL_ERROR "Use a new capture output directory: ${OUT}")
endif()
file(READ "${CONFIG}" data)
string(JSON region GET "${data}" region)
string(JSON point_count LENGTH "${data}" points)
string(JSON trial_count LENGTH "${data}" trials)
if(point_count LESS 1 OR trial_count LESS 1)
  message(FATAL_ERROR "Capture plan must contain points and trials")
endif()
math(EXPR last_point "${point_count}-1")
math(EXPR last_trial "${trial_count}-1")
foreach(index RANGE 0 ${last_point})
  string(JSON point GET "${data}" points ${index})
  list(APPEND points "${point}")
endforeach()
foreach(index RANGE 0 ${last_trial})
  string(JSON id GET "${data}" trials ${index} id)
  if(NOT id MATCHES "^[a-zA-Z0-9_-]+$" OR id IN_LIST ids)
    message(FATAL_ERROR "Invalid or duplicate trial id: ${id}")
  endif()
  list(APPEND ids "${id}")
endforeach()
foreach(index RANGE 0 ${last_trial})
  string(JSON id GET "${data}" trials ${index} id)
  string(JSON tileset GET "${data}" trials ${index} tileset)
  set(options)
  if(NOT tileset STREQUAL "")
    list(APPEND options --tileset "${tileset}")
  endif()
  execute_process(COMMAND "${BIN}/preview.exe" "${region}" ${points} ${options} --out "${OUT}/${id}"
      WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE code)
  if(NOT code EQUAL 0)
    message(FATAL_ERROR "Preview trial ${id} failed: ${code}")
  endif()
endforeach()
configure_file("${CONFIG}" "${OUT}/plan.json" COPYONLY)
execute_process(COMMAND "${BIN}/terrain_tiles_tests.exe" --macro-captures "${OUT}/plan.json" "${OUT}"
    WORKING_DIRECTORY "${ROOT}" RESULT_VARIABLE code)
if(NOT code EQUAL 0)
  message(FATAL_ERROR "Capture verification failed: ${code}")
endif()
message(STATUS "CAPTURES PASS: ${OUT}")
